2018-02-08 15:15:20,668 DEBUG CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime(6) NOT NULL); (params None)
2018-02-08 15:46:49,114 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-08 18:46:22,029 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 12:35:59,826 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 12:36:06,829 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:17:22,327 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:18:53,891 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:19:41,598 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:23:25,689 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:28:44,927 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:46:21,122 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:47:17,370 DEBUG get_location:
2018-02-09 16:47:17,396 WARNING Not Found: /robots.txt
2018-02-09 16:47:19,330 WARNING Not Found: /favicon.ico
2018-02-09 16:47:19,510 WARNING Not Found: /favicon.ico
2018-02-09 16:47:47,876 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:47:53,938 WARNING Not Found: /robots.txt
2018-02-09 16:47:54,273 WARNING Not Found: /favicon.ico
2018-02-09 16:47:54,854 WARNING Not Found: /favicon.ico
2018-02-09 16:48:07,901 DEBUG get_user:
2018-02-09 16:48:38,657 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-09 16:48:41,486 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 12:55:27,896 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 12:55:34,688 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 12:59:44,378 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 12:59:54,003 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 13:02:14,939 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 13:12:19,915 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 13:12:29,591 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 13:46:54,842 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 13:47:07,728 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 13:51:42,201 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:12:20,596 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:13:26,170 WARNING Not Found: /InventoryApp/get_newrequisition/
2018-02-10 14:13:50,917 WARNING Not Found: /InventoryApp/get_newrequisition/
2018-02-10 14:15:34,914 WARNING Not Found: /InventoryApp/add_productquantity/
2018-02-10 14:17:44,077 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:17:48,028 DEBUG add_product_quantity:request is from ip: None
2018-02-10 14:17:48,033 DEBUG add_product_quantity:add_product_quantity:exception details:[<class 'django.db.utils.IntegrityError'>],[(1048, "Column 'locationId_id' cannot be null")]
2018-02-10 14:17:48,033 DEBUG add_product_quantity:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-10 14:18:20,894 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:18:27,230 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:18:30,308 DEBUG add_product_quantity:request is from ip: None
2018-02-10 14:18:30,314 DEBUG add_product_quantity:add_product_quantity:exception details:[<class 'django.db.utils.IntegrityError'>],[(1048, "Column 'locationId_id' cannot be null")]
2018-02-10 14:18:30,314 DEBUG add_product_quantity:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-10 14:19:35,653 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:19:51,109 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:19:59,540 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:20:05,798 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:20:08,823 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 14:20:12,430 DEBUG add_product_quantity:request is from ip: None
2018-02-10 14:20:12,466 DEBUG add_product_quantity:add_product_quantity:exception details:[<class 'django.db.utils.IntegrityError'>],[(1452, 'Cannot add or update a child row: a foreign key constraint fails (`inventoryapp`.`inv_quantity`, CONSTRAINT `inv_quantity_positionId_id_bcce642a_fk_inv_position_id` FOREIGN KEY (`positionId_id`) REFERENCES `inv_position` (`id`))')]
2018-02-10 14:20:12,467 DEBUG add_product_quantity:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-10 18:26:17,843 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 18:26:24,598 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 18:27:05,108 DEBUG search_employees:request is from ip: None
2018-02-10 18:27:05,535 DEBUG update_user:{"error_code":"1", "error_desc": "password updated"}
2018-02-10 18:27:27,085 DEBUG search_employees:request is from ip: None
2018-02-10 18:27:27,442 DEBUG update_user:{"error_code":"1", "error_desc": "password updated"}
2018-02-10 18:27:42,027 DEBUG search_employees:request is from ip: None
2018-02-10 18:27:42,478 DEBUG update_user:{"error_code":"1", "error_desc": "password updated"}
2018-02-10 18:27:56,480 DEBUG search_employees:request is from ip: None
2018-02-10 18:27:56,942 DEBUG update_user:{"error_code":"1", "error_desc": "password updated"}
2018-02-10 18:28:12,784 DEBUG search_employees:request is from ip: None
2018-02-10 18:28:13,254 DEBUG update_user:{"error_code":"1", "error_desc": "password updated"}
2018-02-10 18:45:48,343 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-10 18:47:00,956 WARNING Not Found: /favicon.ico
2018-02-10 19:36:46,922 DEBUG adduser:request is from ip: None
2018-02-10 19:36:47,321 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-10 19:36:47,913 DEBUG search_employees:request is from ip: None
2018-02-10 19:36:47,915 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-10 19:36:47,915 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-10 19:36:48,168 DEBUG search_employees:request is from ip: None
2018-02-10 19:36:48,170 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-10 19:36:48,170 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-10 19:52:12,271 DEBUG adduser:request is from ip: None
2018-02-10 19:52:12,574 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-10 19:52:12,714 DEBUG search_employees:request is from ip: None
2018-02-10 19:52:12,715 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-10 19:52:12,715 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-10 19:52:12,841 DEBUG search_employees:request is from ip: None
2018-02-10 19:52:12,843 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-10 19:52:12,843 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-10 19:52:17,076 DEBUG adduser:request is from ip: None
2018-02-10 19:52:17,470 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-10 19:52:17,834 DEBUG search_employees:request is from ip: None
2018-02-10 19:52:17,835 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-10 19:52:17,835 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-10 19:52:17,899 DEBUG search_employees:request is from ip: None
2018-02-10 19:52:17,900 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-10 19:52:17,900 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-10 19:52:53,298 DEBUG search_employees:request is from ip: None
2018-02-10 19:52:53,303 DEBUG user_details:
2018-02-10 19:53:06,751 DEBUG get_position:
2018-02-10 19:53:11,006 DEBUG get_position:
2018-02-10 19:53:12,643 DEBUG search_employees:request is from ip: None
2018-02-10 19:53:12,647 DEBUG user_details:
2018-02-10 19:53:14,626 DEBUG requsition_details:request is from ip: None
2018-02-10 19:53:14,630 DEBUG requisition:
2018-02-10 19:53:19,189 DEBUG requsition_details:request is from ip: None
2018-02-10 19:53:19,193 DEBUG requisition:
2018-02-10 19:53:23,821 DEBUG requisition:
2018-02-10 19:53:26,571 DEBUG search_employees:request is from ip: None
2018-02-10 19:53:26,575 DEBUG user_details:
2018-02-10 19:53:28,828 DEBUG get_position:
2018-02-10 19:53:30,386 DEBUG get_warehouse:
2018-02-10 19:53:36,105 DEBUG get_position:
2018-02-10 19:53:37,027 DEBUG search_employees:request is from ip: None
2018-02-10 19:53:37,030 DEBUG user_details:
2018-02-10 19:57:02,331 DEBUG add_product:request is from ip: None
2018-02-10 19:57:02,331 DEBUG productname:{"error_code":"2", "error_desc": "Inserting data into products..,productname is mandatory"}
2018-02-10 19:57:10,846 DEBUG search_employees:request is from ip: None
2018-02-10 19:57:10,850 DEBUG user_details:
2018-02-10 19:57:28,961 DEBUG get_position:
2018-02-10 19:57:29,779 DEBUG search_employees:request is from ip: None
2018-02-10 19:57:29,783 DEBUG user_details:
2018-02-10 19:57:34,627 DEBUG search_employees:request is from ip: None
2018-02-10 19:57:34,631 DEBUG user_details:
2018-02-10 19:57:36,130 DEBUG get_position:
2018-02-10 19:57:45,832 DEBUG get_warehouse:
2018-02-10 19:59:11,240 DEBUG get_position:
2018-02-10 19:59:13,095 DEBUG search_employees:request is from ip: None
2018-02-10 19:59:13,099 DEBUG user_details:
2018-02-10 19:59:44,083 DEBUG search_employees:request is from ip: None
2018-02-10 19:59:44,087 DEBUG user_details:
2018-02-10 20:00:14,878 DEBUG adduser:request is from ip: None
2018-02-10 20:00:15,293 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-10 20:00:15,573 DEBUG search_employees:request is from ip: None
2018-02-10 20:00:15,574 DEBUG user_details:
2018-02-10 20:00:15,724 DEBUG search_employees:request is from ip: None
2018-02-10 20:00:15,726 DEBUG user_details:
2018-02-12 12:54:16,553 DEBUG adduser:request is from ip: None
2018-02-12 12:54:16,934 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 12:54:17,164 DEBUG search_employees:request is from ip: None
2018-02-12 12:54:17,165 DEBUG user_details:
2018-02-12 12:54:18,029 DEBUG search_employees:request is from ip: None
2018-02-12 12:54:18,032 DEBUG user_details:
2018-02-12 12:54:55,179 DEBUG adduser:request is from ip: None
2018-02-12 12:54:55,179 DEBUG login_status:{"error_code":"2", "error_desc": "login_inventory.....,passsword is mandatory"}
2018-02-12 12:55:27,990 DEBUG adduser:request is from ip: None
2018-02-12 12:55:28,347 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 12:55:28,514 DEBUG search_employees:request is from ip: None
2018-02-12 12:55:28,515 DEBUG user_details:
2018-02-12 12:55:28,859 DEBUG search_employees:request is from ip: None
2018-02-12 12:55:28,860 DEBUG user_details:
2018-02-12 14:00:36,492 DEBUG adduser:request is from ip: None
2018-02-12 14:00:36,851 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 14:04:14,819 DEBUG adduser:request is from ip: None
2018-02-12 14:04:15,174 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 14:05:05,782 DEBUG adduser:request is from ip: None
2018-02-12 14:05:06,204 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 14:05:06,266 DEBUG search_employees:request is from ip: None
2018-02-12 14:05:06,268 DEBUG user_details:
2018-02-12 14:05:07,093 DEBUG search_employees:request is from ip: None
2018-02-12 14:05:07,097 DEBUG user_details:
2018-02-12 14:05:12,831 DEBUG adduser:request is from ip: None
2018-02-12 14:05:13,254 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 14:05:13,321 DEBUG search_employees:request is from ip: None
2018-02-12 14:05:13,323 DEBUG user_details:
2018-02-12 14:05:13,762 DEBUG search_employees:request is from ip: None
2018-02-12 14:05:13,764 DEBUG user_details:
2018-02-12 14:09:28,011 DEBUG adduser:request is from ip: None
2018-02-12 14:09:28,380 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 14:09:28,475 DEBUG search_employees:request is from ip: None
2018-02-12 14:09:28,477 DEBUG user_details:
2018-02-12 14:09:29,136 DEBUG search_employees:request is from ip: None
2018-02-12 14:09:29,141 DEBUG user_details:
2018-02-12 14:13:39,412 DEBUG adduser:request is from ip: None
2018-02-12 14:13:39,412 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 14:18:25,861 DEBUG adduser:request is from ip: None
2018-02-12 14:18:25,862 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 14:21:33,775 DEBUG adduser:request is from ip: None
2018-02-12 14:21:33,775 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 14:23:58,842 DEBUG adduser:request is from ip: None
2018-02-12 14:23:58,843 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 14:24:11,013 DEBUG adduser:request is from ip: None
2018-02-12 14:24:11,014 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 14:24:17,401 DEBUG adduser:request is from ip: None
2018-02-12 14:24:17,401 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 14:24:21,120 DEBUG adduser:request is from ip: None
2018-02-12 14:24:21,121 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 14:24:32,617 DEBUG adduser:request is from ip: None
2018-02-12 14:24:33,020 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid password"}
2018-02-12 14:24:36,719 DEBUG adduser:request is from ip: None
2018-02-12 14:24:37,136 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 14:24:37,374 DEBUG search_employees:request is from ip: None
2018-02-12 14:24:37,375 DEBUG user_details:
2018-02-12 14:24:37,786 DEBUG search_employees:request is from ip: None
2018-02-12 14:24:37,788 DEBUG user_details:
2018-02-12 15:32:47,928 DEBUG adduser:request is from ip: None
2018-02-12 15:32:48,323 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 15:32:48,592 DEBUG adduser:request is from ip: None
2018-02-12 15:32:48,889 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 15:32:49,243 DEBUG search_employees:request is from ip: None
2018-02-12 15:32:49,247 DEBUG user_details:
2018-02-12 15:32:49,315 DEBUG search_employees:request is from ip: None
2018-02-12 15:32:49,318 DEBUG user_details:
2018-02-12 15:32:49,515 DEBUG search_employees:request is from ip: None
2018-02-12 15:32:49,518 DEBUG user_details:
2018-02-12 15:32:49,520 DEBUG search_employees:request is from ip: None
2018-02-12 15:32:49,523 DEBUG user_details:
2018-02-12 15:34:42,730 DEBUG search_employees:request is from ip: None
2018-02-12 15:34:42,734 DEBUG user_details:
2018-02-12 15:35:04,662 DEBUG search_employees:request is from ip: None
2018-02-12 15:35:04,666 DEBUG user_details:
2018-02-12 15:35:27,493 DEBUG adduser:request is from ip: None
2018-02-12 15:35:27,494 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 15:36:36,831 DEBUG adduser:request is from ip: None
2018-02-12 15:36:36,832 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 15:36:37,818 DEBUG adduser:request is from ip: None
2018-02-12 15:36:37,819 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 15:36:49,471 DEBUG adduser:request is from ip: None
2018-02-12 15:36:49,883 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 15:36:50,184 DEBUG search_employees:request is from ip: None
2018-02-12 15:36:50,186 DEBUG user_details:
2018-02-12 15:36:50,263 DEBUG search_employees:request is from ip: None
2018-02-12 15:36:50,264 DEBUG user_details:
2018-02-12 16:11:37,483 DEBUG adduser:request is from ip: None
2018-02-12 16:11:37,483 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 16:11:50,362 DEBUG adduser:request is from ip: None
2018-02-12 16:11:50,605 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid password"}
2018-02-12 16:12:00,993 DEBUG adduser:request is from ip: None
2018-02-12 16:12:01,273 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid password"}
2018-02-12 16:12:10,181 DEBUG adduser:request is from ip: None
2018-02-12 16:12:10,483 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 16:12:10,563 DEBUG search_employees:request is from ip: None
2018-02-12 16:12:10,564 DEBUG user_details:
2018-02-12 16:12:10,937 DEBUG search_employees:request is from ip: None
2018-02-12 16:12:10,939 DEBUG user_details:
2018-02-12 16:57:20,501 DEBUG adduser:request is from ip: None
2018-02-12 16:57:20,886 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 16:57:23,161 DEBUG search_employees:request is from ip: None
2018-02-12 16:57:23,165 DEBUG user_details:
2018-02-12 16:57:23,167 DEBUG search_employees:request is from ip: None
2018-02-12 16:57:23,171 DEBUG user_details:
2018-02-12 16:57:27,462 DEBUG search_employees:request is from ip: None
2018-02-12 16:57:27,466 DEBUG user_details:
2018-02-12 17:11:11,682 DEBUG add_product:request is from ip: None
2018-02-12 17:11:11,688 DEBUG warehouse_add:add_product:exception details:[<class 'django.db.utils.DataError'>],[(1406, "Data too long for column 'productPackage' at row 1")]
2018-02-12 17:11:11,688 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-12 17:11:37,011 DEBUG add_product:request is from ip: None
2018-02-12 17:11:37,012 DEBUG productname:{"error_code":"2", "error_desc": "Inserting data into products..,productname is mandatory"}
2018-02-12 17:16:19,227 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:16:24,838 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:16:37,644 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:31:43,749 DEBUG add_product:request is from ip: None
2018-02-12 17:31:43,794 DEBUG add_product:{"error_code":"1", "error_desc": "Record added"}
2018-02-12 17:32:30,478 DEBUG adduser:request is from ip: None
2018-02-12 17:32:30,891 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:32:31,869 DEBUG search_employees:request is from ip: None
2018-02-12 17:32:31,871 DEBUG user_details:
2018-02-12 17:32:32,021 DEBUG search_employees:request is from ip: None
2018-02-12 17:32:32,023 DEBUG user_details:
2018-02-12 17:36:31,842 WARNING Not Found: /robots.txt
2018-02-12 17:36:32,122 WARNING Not Found: /favicon.ico
2018-02-12 17:36:32,972 WARNING Not Found: /favicon.ico
2018-02-12 17:39:01,310 DEBUG adduser:request is from ip: None
2018-02-12 17:39:01,720 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:39:01,809 DEBUG search_employees:request is from ip: None
2018-02-12 17:39:01,811 DEBUG user_details:
2018-02-12 17:39:02,233 DEBUG search_employees:request is from ip: None
2018-02-12 17:39:02,235 DEBUG user_details:
2018-02-12 17:44:21,480 DEBUG search_employees:request is from ip: None
2018-02-12 17:44:21,484 DEBUG user_details:
2018-02-12 17:44:29,532 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:44:30,795 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:44:34,099 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:44:37,620 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:44:47,383 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 17:44:52,111 DEBUG search_employees:request is from ip: None
2018-02-12 17:44:52,115 DEBUG user_details:
2018-02-12 17:44:56,260 DEBUG search_employees:request is from ip: None
2018-02-12 17:44:56,263 DEBUG user_details:
2018-02-12 17:45:12,830 DEBUG adduser:request is from ip: None
2018-02-12 17:45:13,164 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:45:15,637 DEBUG adduser:request is from ip: None
2018-02-12 17:45:16,001 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:45:16,108 DEBUG search_employees:request is from ip: None
2018-02-12 17:45:16,109 DEBUG user_details:
2018-02-12 17:45:16,450 DEBUG adduser:request is from ip: None
2018-02-12 17:45:16,746 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:45:16,746 DEBUG adduser:request is from ip: None
2018-02-12 17:45:16,748 DEBUG search_employees:request is from ip: None
2018-02-12 17:45:16,750 DEBUG user_details:
2018-02-12 17:45:17,046 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:45:17,048 DEBUG search_employees:request is from ip: None
2018-02-12 17:45:17,049 DEBUG user_details:
2018-02-12 17:45:17,332 DEBUG search_employees:request is from ip: None
2018-02-12 17:45:17,334 DEBUG user_details:
2018-02-12 17:45:17,353 DEBUG search_employees:request is from ip: None
2018-02-12 17:45:17,354 DEBUG user_details:
2018-02-12 17:45:17,682 DEBUG search_employees:request is from ip: None
2018-02-12 17:45:17,683 DEBUG user_details:
2018-02-12 17:46:32,402 DEBUG search_employees:request is from ip: None
2018-02-12 17:46:32,404 DEBUG user_details:
2018-02-12 17:47:04,794 DEBUG adduser:request is from ip: None
2018-02-12 17:47:05,204 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:47:05,424 DEBUG search_employees:request is from ip: None
2018-02-12 17:47:05,426 DEBUG user_details:
2018-02-12 17:47:05,932 DEBUG search_employees:request is from ip: None
2018-02-12 17:47:05,933 DEBUG user_details:
2018-02-12 17:49:02,623 DEBUG adduser:request is from ip: None
2018-02-12 17:49:02,929 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:49:02,995 DEBUG search_employees:request is from ip: None
2018-02-12 17:49:02,996 DEBUG user_details:
2018-02-12 17:49:03,338 DEBUG search_employees:request is from ip: None
2018-02-12 17:49:03,340 DEBUG user_details:
2018-02-12 17:58:09,345 DEBUG adduser:request is from ip: None
2018-02-12 17:58:09,739 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:58:09,855 DEBUG search_employees:request is from ip: None
2018-02-12 17:58:09,856 DEBUG user_details:
2018-02-12 17:58:10,040 DEBUG adduser:request is from ip: None
2018-02-12 17:58:10,040 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 17:58:10,220 DEBUG search_employees:request is from ip: None
2018-02-12 17:58:10,223 DEBUG user_details:
2018-02-12 17:58:16,254 DEBUG search_employees:request is from ip: None
2018-02-12 17:58:16,256 DEBUG user_details:
2018-02-12 17:59:13,964 DEBUG adduser:request is from ip: None
2018-02-12 17:59:14,329 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 17:59:14,696 DEBUG search_employees:request is from ip: None
2018-02-12 17:59:14,699 DEBUG user_details:
2018-02-12 17:59:14,903 DEBUG search_employees:request is from ip: None
2018-02-12 17:59:14,906 DEBUG user_details:
2018-02-12 18:04:41,301 DEBUG adduser:request is from ip: None
2018-02-12 18:04:41,677 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 18:04:41,900 DEBUG search_employees:request is from ip: None
2018-02-12 18:04:41,902 DEBUG user_details:
2018-02-12 18:04:42,046 DEBUG search_employees:request is from ip: None
2018-02-12 18:04:42,048 DEBUG user_details:
2018-02-12 18:05:31,319 DEBUG adduser:request is from ip: None
2018-02-12 18:05:31,714 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 18:05:32,148 DEBUG search_employees:request is from ip: None
2018-02-12 18:05:32,149 DEBUG user_details:
2018-02-12 18:05:32,946 DEBUG search_employees:request is from ip: None
2018-02-12 18:05:32,949 DEBUG user_details:
2018-02-12 18:08:20,218 DEBUG adduser:request is from ip: None
2018-02-12 18:08:20,630 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 18:08:21,099 DEBUG search_employees:request is from ip: None
2018-02-12 18:08:21,101 DEBUG user_details:
2018-02-12 18:08:21,278 DEBUG search_employees:request is from ip: None
2018-02-12 18:08:21,280 DEBUG user_details:
2018-02-12 18:12:58,653 DEBUG adduser:request is from ip: None
2018-02-12 18:12:58,997 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 18:13:00,282 DEBUG search_employees:request is from ip: None
2018-02-12 18:13:00,286 DEBUG user_details:
2018-02-12 18:13:00,673 DEBUG search_employees:request is from ip: None
2018-02-12 18:13:00,678 DEBUG user_details:
2018-02-12 18:17:17,129 DEBUG adduser:request is from ip: None
2018-02-12 18:17:17,540 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 18:17:17,826 DEBUG search_employees:request is from ip: None
2018-02-12 18:17:17,828 DEBUG user_details:
2018-02-12 18:17:18,190 DEBUG search_employees:request is from ip: None
2018-02-12 18:17:18,193 DEBUG user_details:
2018-02-12 18:34:24,248 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 18:34:26,533 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 18:35:17,261 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 18:35:27,110 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 18:35:35,182 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 18:38:34,812 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-12 18:40:25,524 DEBUG adduser:request is from ip: None
2018-02-12 18:40:25,922 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 18:40:26,026 DEBUG search_employees:request is from ip: None
2018-02-12 18:40:26,027 DEBUG user_details:
2018-02-12 18:40:26,407 DEBUG search_employees:request is from ip: None
2018-02-12 18:40:26,409 DEBUG user_details:
2018-02-12 18:41:47,360 DEBUG adduser:request is from ip: None
2018-02-12 18:41:47,722 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 18:41:47,830 DEBUG search_employees:request is from ip: None
2018-02-12 18:41:47,832 DEBUG user_details:
2018-02-12 18:41:48,256 DEBUG search_employees:request is from ip: None
2018-02-12 18:41:48,258 DEBUG user_details:
2018-02-12 19:35:29,178 DEBUG adduser:request is from ip: None
2018-02-12 19:35:29,179 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-12 19:46:49,346 DEBUG adduser:request is from ip: None
2018-02-12 19:46:49,764 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 19:46:59,543 DEBUG adduser:request is from ip: None
2018-02-12 19:46:59,922 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 19:46:59,954 DEBUG adduser:request is from ip: None
2018-02-12 19:47:00,250 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 19:47:00,953 DEBUG search_employees:request is from ip: None
2018-02-12 19:47:00,955 DEBUG user_details:
2018-02-12 19:47:01,160 DEBUG search_employees:request is from ip: None
2018-02-12 19:47:01,163 DEBUG user_details:
2018-02-12 19:47:01,422 DEBUG search_employees:request is from ip: None
2018-02-12 19:47:01,424 DEBUG user_details:
2018-02-12 19:47:55,968 DEBUG adduser:request is from ip: None
2018-02-12 19:47:56,348 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-12 19:47:56,653 DEBUG search_employees:request is from ip: None
2018-02-12 19:47:56,655 DEBUG user_details:
2018-02-12 19:47:56,752 DEBUG search_employees:request is from ip: None
2018-02-12 19:47:56,753 DEBUG user_details:
2018-02-13 12:15:27,679 DEBUG adduser:request is from ip: None
2018-02-13 12:15:27,679 DEBUG login_status:{"error_code":"2", "error_desc": "login_inventory.....,passsword is mandatory"}
2018-02-13 12:15:33,094 DEBUG adduser:request is from ip: None
2018-02-13 12:15:33,445 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 12:15:33,534 DEBUG search_employees:request is from ip: None
2018-02-13 12:15:33,535 DEBUG user_details:
2018-02-13 12:15:33,966 DEBUG search_employees:request is from ip: None
2018-02-13 12:15:33,967 DEBUG user_details:
2018-02-13 12:15:48,054 DEBUG search_employees:request is from ip: None
2018-02-13 12:15:48,058 DEBUG user_details:
2018-02-13 12:15:50,049 DEBUG get_location:
2018-02-13 12:15:51,413 DEBUG search_employees:request is from ip: None
2018-02-13 12:15:51,418 DEBUG user_details:
2018-02-13 12:15:57,097 DEBUG requsition_details:request is from ip: None
2018-02-13 12:15:57,100 DEBUG requisition:
2018-02-13 12:15:59,815 DEBUG search_employees:request is from ip: None
2018-02-13 12:15:59,818 DEBUG user_details:
2018-02-13 12:53:33,167 DEBUG adduser:request is from ip: None
2018-02-13 12:53:33,519 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 12:53:33,844 DEBUG adduser:request is from ip: None
2018-02-13 12:53:34,148 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 12:53:34,502 DEBUG search_employees:request is from ip: None
2018-02-13 12:53:34,504 DEBUG user_details:
2018-02-13 12:53:34,824 DEBUG search_employees:request is from ip: None
2018-02-13 12:53:34,827 DEBUG user_details:
2018-02-13 12:57:41,978 DEBUG adduser:request is from ip: None
2018-02-13 12:57:42,390 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 12:57:45,238 DEBUG adduser:request is from ip: None
2018-02-13 12:57:45,656 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 12:57:48,852 DEBUG search_employees:request is from ip: None
2018-02-13 12:57:48,856 DEBUG user_details:
2018-02-13 12:57:48,885 DEBUG search_employees:request is from ip: None
2018-02-13 12:57:48,887 DEBUG user_details:
2018-02-13 12:58:02,378 DEBUG requsition_details:request is from ip: None
2018-02-13 12:58:02,381 DEBUG requisition:
2018-02-13 15:15:11,668 DEBUG adduser:request is from ip: None
2018-02-13 15:15:12,019 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:15:12,732 DEBUG search_employees:request is from ip: None
2018-02-13 15:15:12,734 DEBUG user_details:
2018-02-13 15:15:12,873 DEBUG adduser:request is from ip: None
2018-02-13 15:15:13,186 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:15:13,187 DEBUG search_employees:request is from ip: None
2018-02-13 15:15:13,189 DEBUG user_details:
2018-02-13 15:15:13,907 DEBUG search_employees:request is from ip: None
2018-02-13 15:15:13,908 DEBUG user_details:
2018-02-13 15:15:14,181 DEBUG search_employees:request is from ip: None
2018-02-13 15:15:14,185 DEBUG user_details:
2018-02-13 15:19:06,901 DEBUG adduser:request is from ip: None
2018-02-13 15:19:07,282 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:19:07,755 DEBUG search_employees:request is from ip: None
2018-02-13 15:19:07,757 DEBUG user_details:
2018-02-13 15:19:08,211 DEBUG search_employees:request is from ip: None
2018-02-13 15:19:08,215 DEBUG user_details:
2018-02-13 15:20:15,593 DEBUG get_position:
2018-02-13 15:20:15,693 DEBUG get_warehouse:
2018-02-13 15:20:48,122 DEBUG adduser:request is from ip: None
2018-02-13 15:20:48,526 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:21:19,456 DEBUG adduser:request is from ip: None
2018-02-13 15:21:19,864 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:21:20,728 DEBUG search_employees:request is from ip: None
2018-02-13 15:21:20,730 DEBUG user_details:
2018-02-13 15:21:23,552 DEBUG search_employees:request is from ip: None
2018-02-13 15:21:23,557 DEBUG user_details:
2018-02-13 15:21:43,777 DEBUG search_employees:request is from ip: None
2018-02-13 15:21:43,782 DEBUG user_details:
2018-02-13 15:22:55,664 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 15:27:26,912 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 15:30:53,865 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 15:32:56,231 WARNING Not Found: /robots.txt
2018-02-13 15:32:56,878 WARNING Not Found: /favicon.ico
2018-02-13 15:35:32,602 DEBUG adduser:request is from ip: None
2018-02-13 15:35:33,023 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:35:33,867 DEBUG search_employees:request is from ip: None
2018-02-13 15:35:33,868 DEBUG user_details:
2018-02-13 15:35:33,878 DEBUG adduser:request is from ip: None
2018-02-13 15:35:34,191 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:35:34,192 DEBUG search_employees:request is from ip: None
2018-02-13 15:35:34,194 DEBUG user_details:
2018-02-13 15:35:34,891 DEBUG search_employees:request is from ip: None
2018-02-13 15:35:34,892 DEBUG user_details:
2018-02-13 15:35:35,006 DEBUG search_employees:request is from ip: None
2018-02-13 15:35:35,008 DEBUG user_details:
2018-02-13 15:38:31,033 DEBUG adduser:request is from ip: None
2018-02-13 15:38:31,434 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 15:38:32,058 DEBUG search_employees:request is from ip: None
2018-02-13 15:38:32,059 DEBUG user_details:
2018-02-13 15:38:32,168 DEBUG search_employees:request is from ip: None
2018-02-13 15:38:32,170 DEBUG user_details:
2018-02-13 16:14:45,861 DEBUG adduser:request is from ip: None
2018-02-13 16:14:46,281 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 16:14:47,145 DEBUG search_employees:request is from ip: None
2018-02-13 16:14:47,146 DEBUG user_details:
2018-02-13 16:14:47,236 DEBUG search_employees:request is from ip: None
2018-02-13 16:14:47,237 DEBUG user_details:
2018-02-13 16:15:26,416 DEBUG adduser:request is from ip: None
2018-02-13 16:15:26,721 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 16:15:26,808 DEBUG search_employees:request is from ip: None
2018-02-13 16:15:26,810 DEBUG user_details:
2018-02-13 16:15:27,430 DEBUG search_employees:request is from ip: None
2018-02-13 16:15:27,432 DEBUG user_details:
2018-02-13 16:26:17,252 DEBUG adduser:request is from ip: None
2018-02-13 16:26:17,683 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 16:26:18,572 DEBUG search_employees:request is from ip: None
2018-02-13 16:26:18,575 DEBUG user_details:
2018-02-13 16:26:18,859 DEBUG search_employees:request is from ip: None
2018-02-13 16:26:18,863 DEBUG user_details:
2018-02-13 16:29:06,914 DEBUG adduser:request is from ip: None
2018-02-13 16:29:07,328 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 16:29:08,192 DEBUG search_employees:request is from ip: None
2018-02-13 16:29:08,194 DEBUG user_details:
2018-02-13 16:29:08,320 DEBUG search_employees:request is from ip: None
2018-02-13 16:29:08,321 DEBUG user_details:
2018-02-13 16:31:17,691 DEBUG hr_details:
2018-02-13 16:31:18,300 WARNING Not Found: /favicon.ico
2018-02-13 16:35:44,339 DEBUG hr_details:
2018-02-13 16:36:04,141 DEBUG adduser:request is from ip: None
2018-02-13 16:36:04,577 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 16:36:05,407 DEBUG search_employees:request is from ip: None
2018-02-13 16:36:05,411 DEBUG user_details:
2018-02-13 16:36:05,517 DEBUG search_employees:request is from ip: None
2018-02-13 16:36:05,520 DEBUG user_details:
2018-02-13 16:50:52,183 DEBUG adduser:request is from ip: None
2018-02-13 16:50:52,511 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 16:50:53,150 DEBUG search_employees:request is from ip: None
2018-02-13 16:50:53,153 DEBUG user_details:
2018-02-13 16:50:53,269 DEBUG search_employees:request is from ip: None
2018-02-13 16:50:53,270 DEBUG user_details:
2018-02-13 17:30:13,884 DEBUG adduser:request is from ip: None
2018-02-13 17:30:14,275 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 17:30:15,171 DEBUG search_employees:request is from ip: None
2018-02-13 17:30:15,172 DEBUG user_details:
2018-02-13 17:30:15,277 DEBUG search_employees:request is from ip: None
2018-02-13 17:30:15,278 DEBUG user_details:
2018-02-13 17:35:28,115 DEBUG adduser:request is from ip: None
2018-02-13 17:35:28,476 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 17:35:29,401 DEBUG search_employees:request is from ip: None
2018-02-13 17:35:29,402 DEBUG user_details:
2018-02-13 17:35:29,538 DEBUG search_employees:request is from ip: None
2018-02-13 17:35:29,539 DEBUG user_details:
2018-02-13 17:51:59,876 DEBUG adduser:request is from ip: None
2018-02-13 17:52:00,295 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 17:52:01,167 DEBUG search_employees:request is from ip: None
2018-02-13 17:52:01,171 DEBUG user_details:
2018-02-13 17:52:01,278 DEBUG search_employees:request is from ip: None
2018-02-13 17:52:01,282 DEBUG user_details:
2018-02-13 18:13:51,118 DEBUG add_product:request is from ip: None
2018-02-13 18:13:51,174 DEBUG add_product:{"error_code":"1", "error_desc": "Record added"}
2018-02-13 18:15:41,251 DEBUG add_product:request is from ip: None
2018-02-13 18:15:41,251 DEBUG productpackage:{"error_code":"2", "error_desc": "updating data of products..,productpackage is mandatory"}
2018-02-13 18:17:56,807 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 18:18:55,357 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 18:19:05,644 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 18:19:34,426 DEBUG add_product:request is from ip: None
2018-02-13 18:19:34,476 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:19:59,470 DEBUG add_product:request is from ip: None
2018-02-13 18:19:59,470 DEBUG productno:{"error_code":"2", "error_desc": "updating data of products..,productno is mandatory"}
2018-02-13 18:20:13,500 DEBUG add_product:request is from ip: None
2018-02-13 18:20:13,558 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:21:03,161 DEBUG add_product:request is from ip: None
2018-02-13 18:21:03,215 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:25:21,702 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 18:25:28,372 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-13 18:26:06,228 DEBUG add_product:request is from ip: None
2018-02-13 18:26:06,292 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:27:20,539 DEBUG adduser:request is from ip: None
2018-02-13 18:27:20,898 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 18:27:21,387 DEBUG search_employees:request is from ip: None
2018-02-13 18:27:21,389 DEBUG user_details:
2018-02-13 18:27:21,644 DEBUG search_employees:request is from ip: None
2018-02-13 18:27:21,646 DEBUG user_details:
2018-02-13 18:27:35,045 DEBUG add_product:request is from ip: None
2018-02-13 18:27:35,101 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:28:14,681 DEBUG add_product:request is from ip: None
2018-02-13 18:28:14,681 DEBUG productno:{"error_code":"2", "error_desc": "updating data of products..,productno is mandatory"}
2018-02-13 18:28:22,502 DEBUG add_product:request is from ip: None
2018-02-13 18:28:22,549 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:30:56,111 DEBUG search_employees:request is from ip: None
2018-02-13 18:30:56,114 DEBUG user_details:
2018-02-13 18:32:34,326 DEBUG adduser:request is from ip: None
2018-02-13 18:32:34,713 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 18:32:34,909 DEBUG search_employees:request is from ip: None
2018-02-13 18:32:34,910 DEBUG user_details:
2018-02-13 18:32:35,496 DEBUG search_employees:request is from ip: None
2018-02-13 18:32:35,501 DEBUG user_details:
2018-02-13 18:33:27,998 DEBUG add_product:request is from ip: None
2018-02-13 18:33:28,045 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:36:45,718 DEBUG adduser:request is from ip: None
2018-02-13 18:36:46,134 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 18:36:46,892 DEBUG search_employees:request is from ip: None
2018-02-13 18:36:46,894 DEBUG user_details:
2018-02-13 18:36:48,448 DEBUG search_employees:request is from ip: None
2018-02-13 18:36:48,452 DEBUG user_details:
2018-02-13 18:38:51,548 DEBUG add_product:request is from ip: None
2018-02-13 18:38:51,599 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 18:40:20,559 DEBUG adduser:request is from ip: None
2018-02-13 18:40:20,948 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 18:40:21,337 DEBUG search_employees:request is from ip: None
2018-02-13 18:40:21,339 DEBUG user_details:
2018-02-13 18:40:22,604 DEBUG search_employees:request is from ip: None
2018-02-13 18:40:22,605 DEBUG user_details:
2018-02-13 18:40:36,305 DEBUG add_product:request is from ip: None
2018-02-13 18:40:36,358 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-13 19:51:43,701 DEBUG adduser:request is from ip: None
2018-02-13 19:51:44,020 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 19:51:44,684 DEBUG search_employees:request is from ip: None
2018-02-13 19:51:44,686 DEBUG user_details:
2018-02-13 19:51:44,693 DEBUG adduser:request is from ip: None
2018-02-13 19:51:45,014 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-13 19:51:45,015 DEBUG search_employees:request is from ip: None
2018-02-13 19:51:45,016 DEBUG user_details:
2018-02-13 19:51:45,649 DEBUG search_employees:request is from ip: None
2018-02-13 19:51:45,651 DEBUG user_details:
2018-02-13 19:51:45,933 DEBUG search_employees:request is from ip: None
2018-02-13 19:51:45,937 DEBUG user_details:
2018-02-14 12:20:49,820 DEBUG adduser:request is from ip: None
2018-02-14 12:20:50,256 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-14 12:20:51,105 DEBUG search_employees:request is from ip: None
2018-02-14 12:20:51,109 DEBUG user_details:
2018-02-14 12:20:51,236 DEBUG search_employees:request is from ip: None
2018-02-14 12:20:51,240 DEBUG user_details:
2018-02-14 12:33:07,170 DEBUG add_product:request is from ip: None
2018-02-14 12:33:07,228 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-14 12:33:11,660 DEBUG add_product:request is from ip: None
2018-02-14 12:33:11,709 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-14 12:49:20,708 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 12:52:44,840 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 13:52:06,176 DEBUG adduser:request is from ip: None
2018-02-14 13:52:06,514 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid password"}
2018-02-14 13:52:07,899 DEBUG adduser:request is from ip: None
2018-02-14 13:52:08,202 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid password"}
2018-02-14 13:52:08,204 DEBUG adduser:request is from ip: None
2018-02-14 13:52:08,204 DEBUG adduser:request is from ip: None
2018-02-14 13:52:08,506 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid password"}
2018-02-14 13:52:08,815 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid password"}
2018-02-14 13:52:20,502 DEBUG adduser:request is from ip: None
2018-02-14 13:52:20,914 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-14 13:52:20,996 DEBUG search_employees:request is from ip: None
2018-02-14 13:52:20,998 DEBUG user_details:
2018-02-14 13:52:21,734 DEBUG search_employees:request is from ip: None
2018-02-14 13:52:21,736 DEBUG user_details:
2018-02-14 13:52:54,742 DEBUG adduser:request is from ip: None
2018-02-14 13:52:55,079 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-14 13:52:57,848 DEBUG adduser:request is from ip: None
2018-02-14 13:52:58,251 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-14 13:52:58,836 DEBUG search_employees:request is from ip: None
2018-02-14 13:52:58,837 DEBUG user_details:
2018-02-14 13:52:59,024 DEBUG search_employees:request is from ip: None
2018-02-14 13:52:59,025 DEBUG user_details:
2018-02-14 13:53:01,254 DEBUG requsition_details:request is from ip: None
2018-02-14 13:53:01,258 DEBUG requisition:
2018-02-14 15:39:09,806 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 15:39:16,822 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 15:47:54,535 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 15:48:03,928 ERROR Internal Server Error: /InventoryApp/get_hr/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jts-prod/InventoryProject/InventoryApp/views.py", line 558, in get_hr
    cursor.execute("select e.id,e.fullname,j.jobRole from jts_employees e JOIN emp_jobrole j ON e.jobRole_id = j.id where j.jobRole = 'Hr'")
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1054, "Unknown column 'e.jobRole_id' in 'on clause'")
2018-02-14 15:48:04,612 WARNING Not Found: /favicon.ico
2018-02-14 15:48:35,521 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 15:48:39,606 ERROR Internal Server Error: /InventoryApp/get_hr/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jts-prod/InventoryProject/InventoryApp/views.py", line 558, in get_hr
    cursor.execute("select e.id,e.fullname,j.jobRole from jts_employees e JOIN emp_jobrole j ON e.jobRole_id = j.id where j.jobRole = 'Hr'")
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1054, "Unknown column 'e.jobRole_id' in 'on clause'")
2018-02-14 15:50:31,581 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 15:50:35,422 DEBUG hr_details:
2018-02-14 15:51:10,508 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 15:51:14,606 DEBUG hr_details:
2018-02-14 15:54:12,313 DEBUG hr_details:
2018-02-14 15:54:13,850 DEBUG hr_details:
2018-02-14 15:54:28,446 ERROR Internal Server Error: /InventoryApp/get_employee/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jts-prod/InventoryProject/InventoryApp/views.py", line 453, in get_employee
    cursor.execute("select e.id,e.fullName as fullname,e.userName,e.emailId,e.gender,e.bloodGroup,e.dateOfBirth,e.dateOfJoining,e.dateOfExit,e.Address,m.fullName as manager,h.fullName as hrname,e.departmentId,d.departmentName,e.jobRole_id,j.jobRole,e.workLocation_id,w.location from jts_employees e LEFT JOIN jts_employees m ON e.managerId_id = m.id LEFT JOIN jts_employees h ON e.reportingHr_id = h.id JOIN jts_departments d ON e.departmentId = d.id JOIN emp_jobrole j ON e.jobRole_id = j.id JOIN emp_location w ON e.worklocation_id = w.id ORDER BY e.id")
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1054, "Unknown column 'e.jobRole_id' in 'field list'")
2018-02-14 15:57:37,436 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-14 15:58:23,447 DEBUG get_user:
2018-02-14 16:30:46,159 DEBUG get_user:
2018-02-15 13:06:22,519 DEBUG adduser:request is from ip: None
2018-02-15 13:06:22,942 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-15 13:06:23,824 DEBUG search_employees:request is from ip: None
2018-02-15 13:06:23,826 DEBUG user_details:
2018-02-15 13:06:24,046 DEBUG search_employees:request is from ip: None
2018-02-15 13:06:24,047 DEBUG user_details:
2018-02-15 13:07:49,755 DEBUG add_product:request is from ip: None
2018-02-15 13:07:49,849 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-15 13:12:08,935 DEBUG adduser:request is from ip: None
2018-02-15 13:12:09,350 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-15 13:12:10,284 DEBUG search_employees:request is from ip: None
2018-02-15 13:12:10,287 DEBUG user_details:
2018-02-15 13:12:10,335 DEBUG search_employees:request is from ip: None
2018-02-15 13:12:10,339 DEBUG user_details:
2018-02-15 13:32:11,172 DEBUG adduser:request is from ip: None
2018-02-15 13:32:11,179 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-15 13:59:09,225 DEBUG adduser:request is from ip: None
2018-02-15 13:59:09,622 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-15 13:59:10,551 DEBUG search_employees:request is from ip: None
2018-02-15 13:59:10,554 DEBUG user_details:
2018-02-15 13:59:10,620 DEBUG search_employees:request is from ip: None
2018-02-15 13:59:10,624 DEBUG user_details:
2018-02-15 14:02:01,154 DEBUG get_position:
2018-02-15 14:02:08,531 DEBUG get_position:
2018-02-15 14:02:10,774 DEBUG get_warehouse:
2018-02-15 14:03:53,743 DEBUG add_product:request is from ip: None
2018-02-15 14:03:53,797 DEBUG update_product:{"error_code":"1", "error_desc": "record updated"}
2018-02-15 14:04:04,612 DEBUG get_position:
2018-02-15 14:04:07,490 DEBUG search_employees:request is from ip: None
2018-02-15 14:04:07,493 DEBUG user_details:
2018-02-15 14:04:14,542 DEBUG get_position:
2018-02-15 14:04:17,540 DEBUG get_warehouse:
2018-02-15 14:06:04,597 DEBUG get_position:
2018-02-15 14:06:05,218 DEBUG get_warehouse:
2018-02-15 14:06:29,549 DEBUG position_add:request is from ip: None
2018-02-15 14:06:29,608 DEBUG position_add:{"error_code":"1", "error_desc": "Record added"}
2018-02-15 14:06:31,794 DEBUG get_position:
2018-02-15 14:06:33,703 DEBUG get_warehouse:
2018-02-15 14:06:56,743 DEBUG get_warehouse:
2018-02-15 14:50:50,528 DEBUG adduser:request is from ip: None
2018-02-15 14:50:50,962 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-15 14:50:52,128 DEBUG search_employees:request is from ip: None
2018-02-15 14:50:52,132 DEBUG user_details:
2018-02-15 14:50:52,135 DEBUG search_employees:request is from ip: None
2018-02-15 14:50:52,139 DEBUG user_details:
2018-02-15 14:54:34,188 DEBUG adduser:request is from ip: None
2018-02-15 14:54:34,608 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-15 14:54:34,857 DEBUG search_employees:request is from ip: None
2018-02-15 14:54:34,859 DEBUG user_details:
2018-02-15 14:54:35,006 DEBUG search_employees:request is from ip: None
2018-02-15 14:54:35,008 DEBUG user_details:
2018-02-15 16:42:29,319 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:43:42,160 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:49:54,103 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:49:57,377 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:50:18,767 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:57:21,010 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:58:08,939 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:58:19,783 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 16:58:36,954 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:00:18,451 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:00:18,451 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:01:10,542 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:01:10,542 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:02:26,544 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:02:31,095 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:02:47,613 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:02:47,614 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:08:36,892 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:08:42,616 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:09:15,381 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:10:25,129 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:10:54,698 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:10:54,699 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:14:49,332 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:14:52,809 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:16:02,476 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:16:29,780 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:16:29,782 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:19:38,747 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:19:53,968 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:19:53,969 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:20:55,445 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:21:00,318 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:21:01,220 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:21:41,882 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:21:42,784 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:24:31,604 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:26:18,147 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:26:21,445 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:26:34,731 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:27:27,158 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:27:30,146 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:27:30,147 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jts-prod/InventoryProject/InventoryApp/views.py", line 3231, in add_requisitiondetails
    qty.append(quant)
AttributeError: 'tuple' object has no attribute 'append'
2018-02-15 17:28:04,431 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:28:07,713 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:28:14,511 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:28:20,482 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:28:25,178 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:29:05,680 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 17:29:10,427 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:29:11,329 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 17:29:14,542 DEBUG add_requisition_details:request is from ip: None
2018-02-15 17:29:15,444 ERROR Internal Server Error: /InventoryApp/add_requisitiondetails/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view InventoryApp.views.add_requisitiondetails didn't return an HttpResponse object. It returned None instead.
2018-02-15 18:40:37,051 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:40:42,938 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:40:43,607 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:40:51,202 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:42:27,971 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:43:12,909 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:44:48,348 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:45:12,337 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 18:45:26,227 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 19:33:52,161 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-15 19:37:07,082 WARNING Not Found: /robots.txt
2018-02-15 19:37:07,775 WARNING Not Found: /favicon.ico
2018-02-16 12:27:19,651 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:27:33,738 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:30:10,764 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:30:29,627 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:30:37,763 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:53:38,102 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:53:53,046 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:53:59,774 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:55:15,460 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 12:56:15,651 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 13:00:49,113 DEBUG adduser:request is from ip: None
2018-02-16 13:00:49,534 DEBUG adduser:adduser:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: 'hyderabad']
2018-02-16 13:00:49,534 DEBUG add_user:{"error_code":"2", "error_desc": "Failed to add user"}
2018-02-16 13:01:17,219 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 13:01:31,924 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 13:01:38,745 DEBUG adduser:request is from ip: None
2018-02-16 13:01:39,186 DEBUG adduser:adduser:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: 'hyderabad']
2018-02-16 13:01:39,186 DEBUG add_user:{"error_code":"2", "error_desc": "Failed to add user"}
2018-02-16 13:02:15,895 DEBUG adduser:request is from ip: None
2018-02-16 13:02:16,335 DEBUG add_user:{"error_code":"1", "error_desc": "record added"}
2018-02-16 13:04:49,975 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-16 13:04:53,593 DEBUG adduser:request is from ip: None
2018-02-16 13:04:54,074 DEBUG add_user:{"error_code":"1", "error_desc": "record added"}
2018-02-16 13:05:35,607 DEBUG adduser:request is from ip: None
2018-02-16 13:05:35,958 DEBUG add_user:{"error_code":"1", "error_desc": "record added"}
2018-02-16 13:05:58,020 DEBUG adduser:request is from ip: None
2018-02-16 13:05:58,487 DEBUG add_user:{"error_code":"1", "error_desc": "record added"}
2018-02-16 13:06:14,695 DEBUG adduser:request is from ip: None
2018-02-16 13:06:15,050 DEBUG add_user:{"error_code":"1", "error_desc": "record added"}
2018-02-17 11:32:39,736 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 11:32:42,808 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 11:33:13,081 WARNING Not Found: /favicon.ico
2018-02-17 11:33:13,339 WARNING Not Found: /favicon.ico
2018-02-17 11:33:27,285 WARNING Not Found: /robots.txt
2018-02-17 11:33:27,534 WARNING Not Found: /robots.txt
2018-02-17 11:48:39,174 DEBUG adduser:request is from ip: None
2018-02-17 11:48:39,610 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-17 11:48:40,425 DEBUG search_employees:request is from ip: None
2018-02-17 11:48:40,428 DEBUG user_details:
2018-02-17 11:48:40,775 DEBUG search_employees:request is from ip: None
2018-02-17 11:48:40,779 DEBUG user_details:
2018-02-17 11:51:13,403 DEBUG search_employees:request is from ip: None
2018-02-17 11:51:13,407 DEBUG user_details:
2018-02-17 11:51:15,935 DEBUG get_position:
2018-02-17 11:51:18,173 DEBUG get_warehouse:
2018-02-17 11:51:50,341 DEBUG get_position:
2018-02-17 11:52:03,326 DEBUG get_position:
2018-02-17 11:52:06,182 DEBUG search_employees:request is from ip: None
2018-02-17 11:52:06,187 DEBUG user_details:
2018-02-17 11:52:08,465 DEBUG adduser:request is from ip: None
2018-02-17 11:52:08,901 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-17 11:52:09,698 DEBUG search_employees:request is from ip: None
2018-02-17 11:52:09,700 DEBUG user_details:
2018-02-17 11:52:09,769 DEBUG search_employees:request is from ip: None
2018-02-17 11:52:09,771 DEBUG user_details:
2018-02-17 11:53:21,665 DEBUG get_position:
2018-02-17 11:53:29,706 DEBUG get_warehouse:
2018-02-17 11:53:51,977 DEBUG position_add:request is from ip: None
2018-02-17 11:53:52,030 DEBUG position_add:{"error_code":"1", "error_desc": "Record added"}
2018-02-17 11:53:57,063 DEBUG get_position:
2018-02-17 11:53:58,985 DEBUG get_warehouse:
2018-02-17 11:54:07,295 DEBUG update_position:request is from ip: None
2018-02-17 11:54:07,347 DEBUG update_position:{"error_code":"1", "error_desc": "record updated"}
2018-02-17 11:54:11,779 DEBUG get_position:
2018-02-17 11:54:16,588 DEBUG get_warehouse:
2018-02-17 12:01:43,248 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:01:45,531 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:02:24,502 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:04:02,476 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:04:05,258 DEBUG adduser:request is from ip: None
2018-02-17 12:04:05,677 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-17 12:04:06,619 DEBUG search_employees:request is from ip: None
2018-02-17 12:04:06,623 DEBUG user_details:
2018-02-17 12:04:06,756 DEBUG search_employees:request is from ip: None
2018-02-17 12:04:06,760 DEBUG user_details:
2018-02-17 12:04:19,957 DEBUG add_product:request is from ip: None
2018-02-17 12:04:19,961 DEBUG warehouse_add:add_product:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: '']
2018-02-17 12:04:19,961 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-17 12:04:52,845 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:04:56,146 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:04:58,418 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:05:05,081 DEBUG add_product:request is from ip: None
2018-02-17 12:05:05,085 DEBUG warehouse_add:add_product:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: '']
2018-02-17 12:05:05,086 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-17 12:05:18,520 DEBUG add_product:request is from ip: None
2018-02-17 12:05:18,524 DEBUG warehouse_add:add_product:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: '']
2018-02-17 12:05:18,525 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-17 12:05:27,473 DEBUG search_employees:request is from ip: None
2018-02-17 12:05:27,478 DEBUG user_details:
2018-02-17 12:06:05,664 DEBUG add_product:request is from ip: None
2018-02-17 12:06:05,664 DEBUG productname:{"error_code":"2", "error_desc": "Inserting data into products..,productname is mandatory"}
2018-02-17 12:06:15,649 DEBUG add_product:request is from ip: None
2018-02-17 12:06:15,653 DEBUG warehouse_add:add_product:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: '']
2018-02-17 12:06:15,653 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-17 12:26:22,242 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:26:25,755 DEBUG add_product:request is from ip: None
2018-02-17 12:26:25,762 DEBUG warehouse_add:add_product:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: '']
2018-02-17 12:26:25,763 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-17 12:29:16,937 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:29:23,473 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:29:34,228 DEBUG add_product:request is from ip: None
2018-02-17 12:29:34,236 DEBUG add_product:add_product:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: '']
2018-02-17 12:29:34,236 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-17 12:29:41,903 DEBUG search_employees:request is from ip: None
2018-02-17 12:29:41,907 DEBUG user_details:
2018-02-17 12:31:18,908 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:31:26,233 DEBUG add_product:request is from ip: None
2018-02-17 12:31:26,238 DEBUG add_product:add_product:exception details:[<type 'exceptions.ValueError'>],[invalid literal for int() with base 10: '']
2018-02-17 12:31:26,238 DEBUG add_product:{"error_code":"2", "error_desc": "Failed to add record"}
2018-02-17 12:33:21,104 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:33:26,862 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 12:33:34,360 DEBUG add_product:request is from ip: None
2018-02-17 12:33:34,360 DEBUG productno:{"error_code":"2", "error_desc": "Inserting data into products..,productno is mandatory"}
2018-02-17 12:34:41,263 DEBUG add_product:request is from ip: None
2018-02-17 12:34:41,307 DEBUG add_product:{"error_code":"1", "error_desc": "Record added"}
2018-02-17 12:34:45,735 DEBUG get_position:
2018-02-17 12:43:49,954 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-17 17:30:19,755 DEBUG adduser:request is from ip: None
2018-02-17 17:30:19,765 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-17 17:30:23,596 DEBUG adduser:request is from ip: None
2018-02-17 17:30:23,603 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-17 17:31:16,864 DEBUG adduser:request is from ip: None
2018-02-17 17:31:16,870 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-17 17:31:29,562 DEBUG adduser:request is from ip: None
2018-02-17 17:31:29,569 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-17 17:31:45,160 DEBUG adduser:request is from ip: None
2018-02-17 17:31:45,163 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-17 17:31:57,637 DEBUG adduser:request is from ip: None
2018-02-17 17:31:58,050 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-17 17:31:58,208 DEBUG search_employees:request is from ip: None
2018-02-17 17:31:58,210 DEBUG user_details:
2018-02-17 17:31:58,857 DEBUG search_employees:request is from ip: None
2018-02-17 17:31:58,858 DEBUG user_details:
2018-02-17 17:32:00,735 DEBUG requsition_details:request is from ip: None
2018-02-17 17:32:00,738 DEBUG requisition:
2018-02-17 17:32:06,052 DEBUG requsition_details:request is from ip: None
2018-02-17 17:32:06,055 DEBUG requisition:
2018-02-17 18:11:18,361 DEBUG adduser:request is from ip: None
2018-02-17 18:11:18,362 DEBUG username:{"error_code":"2", "error_desc": "login_inventory.....,username is mandatory"}
2018-02-17 18:11:25,063 DEBUG adduser:request is from ip: None
2018-02-17 18:11:25,071 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-17 18:11:40,165 DEBUG adduser:request is from ip: None
2018-02-17 18:11:40,166 DEBUG login_status:{"error_code":"2", "error_desc": "login_inventory.....,passsword is mandatory"}
2018-02-17 18:11:52,862 DEBUG adduser:request is from ip: None
2018-02-17 18:11:53,208 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-17 18:11:54,831 DEBUG search_employees:request is from ip: None
2018-02-17 18:11:54,832 DEBUG user_details:
2018-02-17 18:11:54,835 DEBUG search_employees:request is from ip: None
2018-02-17 18:11:54,837 DEBUG user_details:
2018-02-17 18:11:57,465 DEBUG adduser:request is from ip: None
2018-02-17 18:11:57,853 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-17 18:11:57,946 DEBUG search_employees:request is from ip: None
2018-02-17 18:11:57,947 DEBUG user_details:
2018-02-17 18:11:58,411 DEBUG search_employees:request is from ip: None
2018-02-17 18:11:58,413 DEBUG user_details:
2018-02-19 12:10:39,549 DEBUG adduser:request is from ip: None
2018-02-19 12:10:39,555 DEBUG login_status:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:03:45,512 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-21 20:04:26,201 DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
2018-02-21 20:08:34,650 DEBUG adduser:request is from ip: None
2018-02-21 20:08:35,015 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-21 20:08:35,657 DEBUG search_employees:request is from ip: None
2018-02-21 20:08:35,659 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:08:35,659 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:08:35,828 DEBUG search_employees:request is from ip: None
2018-02-21 20:08:35,829 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:08:35,829 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:09:24,346 DEBUG adduser:request is from ip: None
2018-02-21 20:09:24,661 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-21 20:09:25,296 DEBUG search_employees:request is from ip: None
2018-02-21 20:09:25,298 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:09:25,299 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:09:25,386 DEBUG search_employees:request is from ip: None
2018-02-21 20:09:25,388 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:09:25,388 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:11:14,586 DEBUG search_employees:request is from ip: None
2018-02-21 20:11:14,589 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:11:14,589 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:11:33,935 DEBUG adduser:request is from ip: None
2018-02-21 20:11:34,302 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-21 20:11:34,912 DEBUG search_employees:request is from ip: None
2018-02-21 20:11:34,915 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:11:34,915 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:11:34,991 DEBUG search_employees:request is from ip: None
2018-02-21 20:11:34,994 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:11:34,994 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:14:08,470 DEBUG adduser:request is from ip: None
2018-02-21 20:14:08,889 DEBUG login_status:{"error_code":"1", "error_desc": "login Successfull"}
2018-02-21 20:14:09,698 DEBUG search_employees:request is from ip: None
2018-02-21 20:14:09,702 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:14:09,702 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
2018-02-21 20:14:10,430 DEBUG search_employees:request is from ip: None
2018-02-21 20:14:10,433 DEBUG get_user:get_user:exception details:[<class 'django.db.utils.OperationalError'>],[(1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'inventoryapp.jts_employees.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")]
2018-02-21 20:14:10,433 DEBUG get_user:{"error_code":"2", "error_desc": "Invalid username"}
